"""PyTorch re-implementation of the MATLAB `KSParallelReservoir` package.

This mirrors the algorithmic behaviour in:
  parallelized-reservoir-computing-master/KSParallelReservoir/*.m

Core idea (PRL 120, 024102 (2018)):
- Split Q spatial variables into g contiguous groups of size q = Q/g.
- Reservoir i predicts its local group (size q) but *sees* an input window of
  size Din = q + 2*l consisting of:
    [l points from the left neighbour, its own q points, l points from the right neighbour]
  where l is the *locality* parameter.
- During autonomous prediction, the l boundary values are exchanged with
  neighbouring reservoirs each time step (synchronous update).

Important implementation details preserved from the MATLAB code:
- Each reservoir adjacency matrix A_i is an Erdos-Renyi directed sparse matrix
  generated like MATLAB `sprand`, seeded by (labindex + jobid), and scaled to a
  target spectral radius.
- The input weight matrix Win is not fully random: it is block-structured such
  that each input dimension drives its own block of N/Din reservoir nodes.
  The block weights are generated by reseeding with `rng(i)` for each input i.
- Readout features use the MATLAB "even-index squaring": indices 2,4,6,... are
  squared before linear regression (Python 0-based: 1,3,5,...).

Notes:
- This module is designed for correctness and fidelity to the provided MATLAB
  implementation. The reference MATLAB code was written to run on a MATLAB
  distributed pool (spmd/labSendReceive). Here we simulate the same synchronous
  neighbour exchange on a single process.
- Default dtype is float64 to match MATLAB's `double`.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, List, Optional, Sequence, Tuple

import torch

# Reuse the exact same reservoir generator + block-input implementation as the
# single-reservoir PyTorch port.
from ks_basic_single_reservoir_torch import (
    generate_reservoir_sparse,
    make_block_input_weights,
)


def _as_device(device: Optional[torch.device | str]) -> torch.device:
    if device is None:
        return torch.device("cpu")
    return device if isinstance(device, torch.device) else torch.device(device)


@dataclass(frozen=True)
class KSParallelParams:
    """Parameter bundle matching the MATLAB `resparams` structure."""

    # Global spatiotemporal system dimension
    Q: int

    # Parallelization
    g: int
    locality: int

    # Reservoir
    approx_reservoir_size: int = 5000
    radius: float = 0.6
    degree: float = 3.0
    beta: float = 1e-4

    # Time lengths
    discard_length: int = 1000
    train_length: int = 79_000
    predict_length: int = 2999

    # Input scaling (MATLAB script multiplies the data by sigma)
    sigma: float = 0.5

    # Randomization
    jobid: int = 1


@torch.no_grad()
def _augment_even_square_inplace(X: torch.Tensor) -> torch.Tensor:
    """Apply MATLAB's `states(2:2:N,:) = states(2:2:N,:).^2` feature map.

    Python 0-based indices: 1,3,5,... are squared.
    Works for vectors [N] and matrices [N, T].
    """
    X[1::2].square_()
    return X


def _build_local_indices(Q: int, g: int, locality: int) -> Tuple[int, int, List[List[int]]]:
    """Return (chunk_size, Din, indices_per_reservoir).

    Reservoir i (0-based) is responsible for global indices:
      chunk = [i*chunk_size, ..., (i+1)*chunk_size-1]
    and sees inputs:
      [rear_overlap (l), chunk (q), forward_overlap (l)]
    with periodic wrap.

    This matches `indexing_function_rear/forward.m` + the assembly in
    `parallel_reservoir_benchmarking.m`.
    """
    if Q <= 0:
        raise ValueError("Q must be positive")
    if g <= 0:
        raise ValueError("g must be positive")
    if Q % g != 0:
        raise ValueError("Q must be divisible by g")
    if locality < 0:
        raise ValueError("locality must be >= 0")

    chunk_size = Q // g
    if locality > chunk_size:
        raise ValueError("locality must be <= chunk_size (overlap cannot exceed chunk)")

    Din = chunk_size + 2 * locality
    indices: List[List[int]] = []
    for i in range(g):
        begin = i * chunk_size
        end = begin + chunk_size - 1
        rear = [((begin - locality) + k) % Q for k in range(locality)]
        chunk = list(range(begin, end + 1))
        front = [((end + 1) + k) % Q for k in range(locality)]
        indices.append(rear + chunk + front)

    return chunk_size, Din, indices


class KSParallelReservoir(torch.nn.Module):
    """Parallel reservoir system reproducing MATLAB `KSParallelReservoir`.

    Typical workflow:
        model = KSParallelReservoir(params)
        model.fit(u_train)  # u_train: [Q, T_train]
        pred = model.predict_intervals(u_test, warmup_starts=[...], sync_length=32)

    Shapes:
        - Global data u: [Q, T]
        - Per-reservoir input window h_i: [Din, T]
        - Per-reservoir output g_i: [chunk_size, T]
    """

    def __init__(
        self,
        params: KSParallelParams,
        *,
        device: Optional[torch.device | str] = None,
        dtype: torch.dtype = torch.float64,
        power_iter: int = 100,
    ) -> None:
        super().__init__()

        dev = _as_device(device)

        chunk_size, Din, idx = _build_local_indices(params.Q, params.g, params.locality)

        # Match MATLAB script: nodes_per_input = round(approx_reservoir_size / Din)
        nodes_per_input = int(round(float(params.approx_reservoir_size) / float(Din)))
        nodes_per_input = max(nodes_per_input, 1)

        N = nodes_per_input * Din

        self.params = params
        self.device = dev
        self.dtype = dtype
        self.power_iter = int(power_iter)

        self.Q = int(params.Q)
        self.g = int(params.g)
        self.locality = int(params.locality)
        self.chunk_size = int(chunk_size)
        self.Din = int(Din)
        self.nodes_per_input = int(nodes_per_input)
        self.N = int(N)

        # Shared block-structured input weights (MATLAB uses ip = (-1+2*rand), no sigma here;
        # sigma is applied to data externally).
        w_in_diag = make_block_input_weights(
            reservoir_size=self.N,
            num_inputs=self.Din,
            sigma=1.0,
            device=self.device,
            dtype=self.dtype,
        )
        self.register_buffer("w_in_diag", w_in_diag)

        # Per-reservoir adjacency matrices A_i (sparse) and readouts Wout_i.
        self.As: List[torch.Tensor] = []
        self.w_outs: List[torch.Tensor] = []
        self.states: List[torch.Tensor] = []

        for i in range(self.g):
            seed_A = int((i + 1) + params.jobid)  # MATLAB: rng(labindex + jobid), labindex starts at 1
            A_i = generate_reservoir_sparse(
                size=self.N,
                radius=float(params.radius),
                degree=float(params.degree),
                seed=seed_A,
                device=self.device,
                dtype=self.dtype,
                power_iter=self.power_iter,
            )
            self.As.append(A_i)
            self.w_outs.append(torch.zeros((self.chunk_size, self.N), device=self.device, dtype=self.dtype))
            self.states.append(torch.zeros((self.N,), device=self.device, dtype=self.dtype))

        self._indices_per_reservoir = idx
        self._central_slice = slice(self.locality, self.locality + self.chunk_size)

    # ---------------------------- helpers ----------------------------

    @torch.no_grad()
    def _input_term(self, u: torch.Tensor) -> torch.Tensor:
        """Compute Win @ u efficiently for the block-structured Win."""
        if u.ndim != 1 or u.shape[0] != self.Din:
            raise ValueError(f"u must have shape [{self.Din}]")
        # Repeat each input value nodes_per_input times.
        u_rep = u.repeat_interleave(self.nodes_per_input)
        return self.w_in_diag * u_rep

    @torch.no_grad()
    def _step(self, i: int, x: torch.Tensor, u: torch.Tensor) -> torch.Tensor:
        """x <- tanh(A_i x + Win u)."""
        Ax = torch.sparse.mm(self.As[i], x.unsqueeze(1)).squeeze(1)
        return torch.tanh(Ax + self._input_term(u))

    def _ensure_global_shape(self, u: torch.Tensor) -> torch.Tensor:
        """Accept [Q,T] or [T,Q] and return [Q,T] on device/dtype."""
        if u.ndim != 2:
            raise ValueError("u must be 2D")
        if u.shape[0] == self.Q:
            U = u
        elif u.shape[1] == self.Q:
            U = u.T
        else:
            raise ValueError(f"u must have shape [Q,T] or [T,Q] with Q={self.Q}")
        return U.to(device=self.device, dtype=self.dtype)

    # ---------------------------- training ----------------------------

    @torch.no_grad()
    def fit(self, u_train: torch.Tensor, *, identical_reservoirs: bool = False, time_chunk: int = 256) -> "KSParallelReservoir":
        """Train all reservoirs' readouts via ridge regression.

        This reproduces `train_reservoir.m` + `fit.m`.

        Args:
            u_train: global training data, shape [Q,T] (or [T,Q]).
            identical_reservoirs: if True, train only reservoir 0 and copy its
                (A, Wout) to all reservoirs. This corresponds to the PRL's
                translation-invariant shortcut for mu=0 (not the default MATLAB
                benchmarking script).
            time_chunk: chunk size (in time) used to accumulate X X^T and Y X^T.

        Returns:
            self
        """
        U = self._ensure_global_shape(u_train)
        T = int(U.shape[1])
        need = int(self.params.discard_length + self.params.train_length)
        if T < need:
            raise ValueError(f"Need at least discard_length+train_length={need} time steps, got {T}")
        if time_chunk <= 0:
            raise ValueError("time_chunk must be positive")

        def train_one(res_idx: int) -> Tuple[torch.Tensor, torch.Tensor]:
            # Local input window h_i(t) (includes overlaps) for the required training horizon.
            loc_idx = self._indices_per_reservoir[res_idx]
            data = (float(self.params.sigma) * U[loc_idx, :need]).contiguous()  # [Din, need]

            x = torch.zeros((self.N,), device=self.device, dtype=self.dtype)

            # Discard transient.
            for t in range(int(self.params.discard_length)):
                x = self._step(res_idx, x, data[:, t])

            # Accumulate Gram matrix and cross-covariance using chunks.
            S = torch.zeros((self.N, self.N), device=self.device, dtype=self.dtype)
            YX = torch.zeros((self.chunk_size, self.N), device=self.device, dtype=self.dtype)

            train_len = int(self.params.train_length)
            disc = int(self.params.discard_length)
            processed = 0

            while processed < train_len:
                L = min(int(time_chunk), train_len - processed)

                X = torch.empty((self.N, L), device=self.device, dtype=self.dtype)

                for j in range(L):
                    X[:, j] = x
                    global_j = processed + j
                    if global_j < train_len - 1:
                        x = self._step(res_idx, x, data[:, disc + global_j])

                Phi = X
                _augment_even_square_inplace(Phi)

                Y = data[self._central_slice, disc + processed : disc + processed + L]  # [chunk_size, L]

                S.addmm_(Phi, Phi.T)
                YX.addmm_(Y, Phi.T)

                processed += L

            # Ridge regression: Wout = YX (S + beta I)^{-1}
            beta = float(self.params.beta)
            if beta > 0:
                S = S + beta * torch.eye(self.N, device=self.device, dtype=self.dtype)

            Lchol = torch.linalg.cholesky(S)
            w_out_T = torch.cholesky_solve(YX.T, Lchol)
            w_out = w_out_T.T.contiguous()

            return w_out, x

        if identical_reservoirs:
            w_out0, _ = train_one(0)
            A0 = self.As[0]
            for i in range(self.g):
                self.As[i] = A0
                self.w_outs[i] = w_out0
            return self

        for i in range(self.g):
            w_out, _ = train_one(i)
            self.w_outs[i] = w_out

        return self

    # ---------------------------- prediction ----------------------------

    @torch.no_grad()
    def predict_one_interval(
        self,
        u_test: torch.Tensor,
        *,
        warmup_start: int,
        sync_length: int = 32,
        predict_length: Optional[int] = None,
    ) -> torch.Tensor:
        """Predict a single interval using synchronous neighbour exchange.

        This reproduces `synchronize.m` + `predict.m` in behaviour.

        Args:
            u_test: global test data [Q,T] (or [T,Q]). Only used for warm-up.
            warmup_start: 0-based time index of the first warm-up sample.
                For consistency with the MATLAB benchmarking code:
                  - MATLAB uses `data(:, prediction_marker + i)` for i=1..sync_length.
                  - If `prediction_marker` is a 1-based index, then the *first* warmup
                    sample is at MATLAB index prediction_marker+1, which corresponds
                    to Python index prediction_marker.
                Therefore, if you load `prediction_marker` values from the MATLAB
                `.mat` file, you typically pass them directly as `warmup_start`.
            sync_length: number of teacher-forced warm-up steps.
            predict_length: number of autonomous prediction steps. If None, use
                params.predict_length.

        Returns:
            pred_global: tensor of shape [Q, predict_length], concatenated in
                reservoir order.
        """
        U = self._ensure_global_shape(u_test)
        T = int(U.shape[1])

        pl = int(self.params.predict_length if predict_length is None else predict_length)
        if pl <= 0:
            raise ValueError("predict_length must be positive")
        if sync_length < 0:
            raise ValueError("sync_length must be >= 0")

        # Need warmup samples plus prediction horizon for ground truth comparisons.
        if warmup_start < 0 or warmup_start + sync_length + pl > T:
            raise ValueError("warmup_start+sync_length+predict_length must fit within u_test")

        # --- Warm-up (teacher forcing on true measurements) ---
        states = [torch.zeros((self.N,), device=self.device, dtype=self.dtype) for _ in range(self.g)]

        sigma = float(self.params.sigma)
        for t in range(int(sync_length)):
            tt = int(warmup_start + t)
            for i in range(self.g):
                loc_idx = self._indices_per_reservoir[i]
                u_loc = sigma * U[loc_idx, tt]
                states[i] = self._step(i, states[i], u_loc)

        # --- Autonomous prediction with neighbour exchange ---
        pred = torch.empty((self.Q, pl), device=self.device, dtype=self.dtype)

        for k in range(pl):
            outs: List[torch.Tensor] = []
            for i in range(self.g):
                x_aug = states[i].clone()
                _augment_even_square_inplace(x_aug)
                outs.append(self.w_outs[i] @ x_aug)  # [chunk_size]

            # Collect global output.
            pred[:, k] = torch.cat(outs, dim=0)

            # Synchronous boundary exchange and state update.
            new_states: List[torch.Tensor] = []
            for i in range(self.g):
                if self.locality > 0:
                    rear = outs[(i - 1) % self.g][-self.locality :]
                    front = outs[(i + 1) % self.g][: self.locality]
                    feedback = torch.cat([rear, outs[i], front], dim=0)
                else:
                    feedback = outs[i]
                new_states.append(self._step(i, states[i], feedback))

            states = new_states

        return pred

    @torch.no_grad()
    def predict_intervals(
        self,
        u_test: torch.Tensor,
        *,
        warmup_starts: Sequence[int],
        sync_length: int = 32,
        predict_length: Optional[int] = None,
    ) -> torch.Tensor:
        """Predict multiple non-overlapping intervals and concatenate outputs.

        Matches the MATLAB pattern:
            pred_collect(:, (k-1)*pl+1:k*pl) = prediction
            collated_prediction = gcat(pred_collect, 1, 1)

        Args:
            u_test: global test data [Q,T] (or [T,Q]). Used only for warm-up.
            warmup_starts: list of warm-up start indices (see `predict_one_interval`).
            sync_length: warm-up length.
            predict_length: steps per interval.

        Returns:
            pred_all: [Q, len(warmup_starts)*predict_length]
        """
        pl = int(self.params.predict_length if predict_length is None else predict_length)
        preds = [
            self.predict_one_interval(
                u_test,
                warmup_start=int(s),
                sync_length=sync_length,
                predict_length=pl,
            )
            for s in warmup_starts
        ]
        return torch.cat(preds, dim=1)


@torch.no_grad()
def rmse_over_space(true_u: torch.Tensor, pred_u: torch.Tensor) -> torch.Tensor:
    """Compute RMSE across the spatial dimension at each time step.

    Args:
        true_u: [Q,T]
        pred_u: [Q,T]

    Returns:
        rmse: [T]
    """
    if true_u.shape != pred_u.shape:
        raise ValueError("Shapes must match")
    return torch.sqrt(torch.mean((true_u - pred_u) ** 2, dim=0))
